use std::fs;
use std::path::Path;
use xtask_watch::anyhow::Result;

#[derive(serde::Deserialize)]
struct GitHubItem {
    name: String,
    #[serde(rename = "download_url")]
    download_url: Option<String>,
}

pub fn run() -> Result<()> {
    let workspace_root = Path::new(env!("CARGO_MANIFEST_DIR")).parent().unwrap();
    let themes_dir = workspace_root.join("themes");
    fs::create_dir_all(&themes_dir)?;

    let api_url =
        "https://api.github.com/repos/helix-editor/helix/contents/runtime/themes?ref=master";
    log::info!("listing themes from {api_url}");

    let config = ureq::config::Config::builder()
        .user_agent("explorer-xtask")
        .build();
    let agent = ureq::Agent::new_with_config(config);
    let body = agent.get(api_url).call()?.into_body().read_to_string()?;
    let items: Vec<GitHubItem> = serde_json::from_str(&body)?;

    let mut theme_names: Vec<String> = Vec::new();
    for item in &items {
        if !item.name.ends_with(".toml") {
            continue;
        }
        let Some(url) = &item.download_url else {
            continue;
        };
        log::info!("  downloading {}", item.name);
        let resp = agent.get(url).call()?;
        let path = themes_dir.join(&item.name);
        fs::write(&path, resp.into_body().read_to_string()?)?;
        theme_names.push(item.name.trim_end_matches(".toml").to_string());
    }
    theme_names.sort();

    generate_themes_rs(&themes_dir, &theme_names)?;
    log::info!(
        "downloaded {} themes to {}",
        theme_names.len(),
        themes_dir.display()
    );
    Ok(())
}

fn generate_themes_rs(themes_dir: &Path, names: &[String]) -> Result<()> {
    let mut entries = String::new();
    for name in names {
        entries.push_str(&format!(
            "    (\"{name}\", include_str!(\"{name}.toml\")),\n"
        ));
    }
    let content = format!(
        "// Generated by `cargo xtask update-themes` — do not edit.\n\
         pub const THEMES: &[(&str, &str)] = &[\n\
         {entries}];\n"
    );
    fs::write(themes_dir.join("themes.rs"), content)?;
    Ok(())
}
